// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSwyavj8WPynZFPo5g9hxFAgkymXtiEfc',
    appId: '1:830230399727:web:e010284358aa20c389e91a',
    messagingSenderId: '830230399727',
    projectId: 'socialmediaapp-4933f',
    authDomain: 'socialmediaapp-4933f.firebaseapp.com',
    storageBucket: 'socialmediaapp-4933f.appspot.com',
    measurementId: 'G-ZKTP6H3FC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEFXmCvOz-Lxsf9HoflB-PNKrdfnlmQWc',
    appId: '1:830230399727:android:621fe383301d481f89e91a',
    messagingSenderId: '830230399727',
    projectId: 'socialmediaapp-4933f',
    storageBucket: 'socialmediaapp-4933f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWaH-G4-N-G0ZNzQoVnEoJvwtVdXgXT4o',
    appId: '1:830230399727:ios:2b9cadc9448c667589e91a',
    messagingSenderId: '830230399727',
    projectId: 'socialmediaapp-4933f',
    storageBucket: 'socialmediaapp-4933f.appspot.com',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWaH-G4-N-G0ZNzQoVnEoJvwtVdXgXT4o',
    appId: '1:830230399727:ios:79906d2ff0db142989e91a',
    messagingSenderId: '830230399727',
    projectId: 'socialmediaapp-4933f',
    storageBucket: 'socialmediaapp-4933f.appspot.com',
    iosBundleId: 'com.example.firstProject.RunnerTests',
  );
}
